### ISSUE TITLE
All generated link return 404 not found

### ISSUE THREAD

**Issue by piptravels** [AndrewPaglusch/FlashPaper#113]
I thought everything was working (since it generated the link, etc) however when I tried to test by opening the link I'm consistently getting this error page. Sorry I failed to actually test it. Any ideas other than OE (operator error)?
![9](https://user-images.githubusercontent.com/14855599/221432757-a09ea3db-5d52-4c87-99e6-57fe186d8b42.png)

**Comment by AndrewPaglusch** [comment]
Does the main FlashPaper page load when you go directly to "https://flash.link2view.com/flashpaper/"?

**Comment by piptravels** [comment]
> Does the main FlashPaper page load when you go directly to "https://flash.link2view.com/flashpaper/"?
> 
> Edit: Since your site is public, I was able to test. Try removing "/flashpaper" from the `base_url`. I believe that will fix your problem.

You're a genius. worked like a charm. Please send the best method to financially support the project, thanks again

**Comment by AndrewPaglusch** [comment]
Hey @piptravels I'm really happy to hear that that resolved your problem! Donation information is [here](https://github.com/AndrewPaglusch/FlashPaper#donations). Thank you very much
