### ISSUE TITLE
ARM image

### ISSUE THREAD

**Issue by Pietro395** [AndrewPaglusch/FlashPaper#143]
Is it possible to start the container with docker-compose on ARM?

Testing it I get this error:
`ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by AndrewPaglusch** [comment]
Hey @Pietro395, thanks for opening this issue. Let me check this out and get back with you.

**Comment by AndrewPaglusch** [comment]
Quick update: I was able to reproduce this issue on a ARM box
```
$ /opt/docker]# docker-compose up -d
Creating network "docker_default" with the default driver
Pulling flashpaper (ghcr.io/andrewpaglusch/flashpaper:v2)...
v2: Pulling from andrewpaglusch/flashpaper
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by Pietro395** [comment]
Thank you!
Let me know as soon as you need a test from me

**Comment by AndrewPaglusch** [comment]
I'll let you know. We're just waiting on a review from @mattburchett right now on PR #144

**Comment by AndrewPaglusch** [comment]
@Pietro395 I'm ready for you to test. I just tested on the `master` tag on a RPi and it seems to be working for me. I'd like to hear if it's working for you as well. If so, I'll cut a new release.

**Comment by Pietro395** [comment]
> @Pietro395 I'm ready for you to test. I just tested on the `master` tag on a RPi and it seems to be working for me. I'd like to hear if it's working for you as well. If so, I'll cut a new release.

Tried it and the container starts without any problems.

I have not yet tested the functionality but will do so shortly.

Thank you very much!

**Comment by Pietro395** [comment]
I confirm that everything works as expected :)
