### ISSUE TITLE
Message size limits?

### ISSUE THREAD

**Issue by mitchellknight** [AndrewPaglusch/FlashPaper#32]
What are the limits for _input length_? I've run in to the following error multiple times.

> Input length too long 

Can a counter (e.g. 2456/10000 characters) be added so we know when we're close to the limitation? The <textarea> could also be given a maxlength.

**Comment by AndrewPaglusch** [comment]
The input length limit (along with a few other settings) is defined in the `index.php` file. I really like the idea of limiting the `<textarea>` character length to match the configured limit.

```
#Settings
define('RETURN_FULL_URL', true);
define('MAX_INPUT_LENGTH', 3000);
define('DATA_DIR', 'data');
```

**Comment by AndrewPaglusch** [comment]
`maxlength` is now enforced in PR #31
