### ISSUE TITLE
Onboarding Message

### ISSUE THREAD

**Issue by mitchellknight** [AndrewPaglusch/FlashPaper#33]
I think the copy could provide a more self-explanatory user experience.

**Create New**

- Self-Destructing Message → Create A New Self-Destructing Message
- Submit → Encrypt Message

**Self-Destructing URL**

- Needs some language to explain what to do next. It's not obvious to an end-user that the URL isn't automatically shared with the host.: e.g. “Share this URL via email, chat or other messaging service. It will self-destruct after being viewed once.”

**Comment by AndrewPaglusch** [comment]
Addressed in PR #36
