### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by mitchellknight** [AndrewPaglusch/FlashPaper#34]
It would be nice if we could customize the style and some basic settings with a YAML configuration file or something similar.

Some of the details I'd like to customize:

- Automatically redirect to HTTPS
- Page <title>
- Add a simple announcement message
- Stylesheet (e.g. load theme.css to customize look and feel)

Doing it this way makes software updates (without losing settings) easier.

**Comment by AndrewPaglusch** [comment]
Working on this in #37

**Comment by AndrewPaglusch** [comment]
Closing - Implemented in #37
