### ISSUE TITLE
Suggestion: Change "requirements" section

### ISSUE THREAD

**Issue by red-erik** [AndrewPaglusch/FlashPaper#39]
Hello,
thank you for this lightweight and very useful software.
I'm running it on Windows 2016 with IIS and PHP 7.x and it works perfectly so having Linux as a requirement should not be necessary.
Regards,

Red.

**Comment by AndrewPaglusch** [comment]
I'm very happy to hear that you enjoy using FlashPaper! You're the second person I've heard from that's hosting it on Windows, so I will gladly remove "Linux" as a requirement. Thank you for the suggestion!

**Comment by AndrewPaglusch** [comment]
Resolved: 2af557f
