### ISSUE TITLE
Configure generated links to use full domain instead of private hostame?

### ISSUE THREAD

**Issue by hunsbct** [AndrewPaglusch/FlashPaper#94]
I'm running the application in a docker container and had no issues getting it to work via reverse proxy, but the links that are being generated are using the hostname and mapped port instead of the full domain. So for example, the site is https://website.com/flashpaper but the URL is http://hostname:8989/?k=abcdef...

I am not seeing any information on how to configure the software to use a specific server or domain name for the generated URLs. Is this currently implemented?

**Comment by AndrewPaglusch** [comment]
Hey @hunsbct, thanks for reaching out! I helped someone else with a similar problem here: #60. That might help you figure this out. What reverse proxy are you using in front of FlashPaper?

**Comment by hunsbct** [comment]
I'm using nginx, and coincidentally landed on the same host header solution just before I came back here. That's getting me much closer, but now my URLs are coming up as https://website.com/?k=abcdef rather than https://website.com/flashpaper/?k=abcdef

I'm trying to see if there's a way at the nginx layer to add the /flashpaper slug but that may not be possible

**Comment by AndrewPaglusch** [comment]
Can you try changing `location / {` to `location /flashpaper/ {` in Nginx to see if that makes any difference? If not, I'm going to try to replicate your setup locally and figure it out for you.

**Comment by hunsbct** [comment]
Sorry, I should have included that before. It currently is using that location:

```
location /flashpaper/ {
	proxy_pass http://hostname:8989/;
	proxy_set_header Host $host;
}
```

I appreciate your help so far. Let me know if there's any other info or testing I can assist with. Ultimately we could probably just use a subdomain for this if need be.

**Comment by hunsbct** [comment]
Quick addition there as well, I did try adding /flashpaper to the end of the proxy_pass line as suggested as well as at the end of the proxy_set_header line, both of which break access to the application itself. The former will fail because the docker server is serving it on port 8989 without the URL slug, and the latter presumably because it's trying to reach https://website.com/flashpaper/flashpaper behind the scenes

**Comment by AndrewPaglusch** [comment]
@hunsbct I've been thinking about implementing an _override_ setting like that. It would allow the user to set the FQDN and path that should be used when creating the retrieval URL. If the setting is not set, FlashPaper will default to the current behavior of automatically generating the URL based on the information it has available. 

I still would like to figure out the problem you're having, but I will probably end up adding this feature as well to make it easier for people to fix in the future.

**Comment by AndrewPaglusch** [comment]
Hey @hunsbct, @joshuanave and I just spent multiple hours tonight trying to find an elegant fix to this problem. We ultimately decided that the best way to correct this problem is to add the feature I mentioned in my last comment. Please see if [v2.1.0](https://github.com/AndrewPaglusch/FlashPaper/releases/tag/v2.1.0) solves your problem.

**Comment by hunsbct** [comment]
Resolved! Thanks for taking the time to add this feature.

**Comment by AndrewPaglusch** [comment]
You're very welcome!
